[tool.poetry]
name = "utils"
version = "0.1.0"
description = ""
authors = ["hakomori64 <hakomori64@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
Jinja2 = "^3.0.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
